version: "3.5"

services:
  comment-read-service:
    build: 
      context: .
      dockerfile: docker/Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        #USER_UID: 1000
        #USER_GID: 1000
        TEST: 1000
    container_name: comment-read-service
    ports:
      - "9042:9042"
    environment:
      - PROFILE=production
    networks:
      - commentReadService
      - commentReadRepo
networks:
  commentReadService:
    name: commentReadService
  commentReadRepo:
    external:
      name: commentReadRepo