server:
  port: 9997
spring:
  application:
    name: commentReadService
  cache:
    type: redis
    redis:
      time-to-live: 5000
      cache-null-values: false
      use-key-prefix: false
  redis:
    host: redis
    port: 6379

repo:
  uri: "http://localhost:9998"

---

spring:
  config:
    name: dev

